### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by nachiketbhuta** [arghyadeep99/Go-Karuna-Go#1]
Can we add the same to a Discord Server ?

**Comment by arghyadeep99** [comment]
Yes, @nachiketbhuta. There will be a requirement of slight code change. I have used slack_client.py for managing with Slack. You can do the same with Discord and use its webhook, and use appropriate libraries.

**Comment by nachiketbhuta** [comment]
OK. I'll look into it. ;)

**Comment by arghyadeep99** [comment]
Also, you can look at the future scope mentioned in README. They are doable too.

**Comment by nachiketbhuta** [comment]
https://discord.gg/4APZ4x7
Join the discord server
